"""Initial migration.

Revision ID: e75633f017b8
Revises: 
Create Date: 2023-07-27 12:44:39.230715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e75633f017b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_details', schema=None) as batch_op:
        batch_op.drop_constraint('flight_details_ibfk_1', type_='foreignkey')
        batch_op.drop_column('watchlistId')

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flightDetailsId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'flight_details', ['flightDetailsId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flightDetailsId')

    with op.batch_alter_table('flight_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watchlistId', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('flight_details_ibfk_1', 'watchlist', ['watchlistId'], ['id'])

    # ### end Alembic commands ###
